services:
  - type: web
    name: dgfarmer-api
    runtime: docker
    plan: free
    region: frankfurt
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: PORT
        value: 8080
      - key: Jwt__Key
        sync: false
      - key: Jwt__Issuer
        value: DgFarmerApi
      - key: Jwt__Audience
        value: DgFarmerApp
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
